version: '3.8'
services:
  peer1:
    build: .
#    image: datasavenet-peer1
    ports:
      - "8081:8080"
    networks:
      - p2pnet

  peer2:
    build: .
#    image: datasavenet-peer1
    ports:
      - "8082:8080"
    networks:
      - p2pnet

  peer3:
    build: .
#    image: datasavenet-peer1
    ports:
      - "8083:8080"
    networks:
      - p2pnet


networks:
  p2pnet:
    driver: bridge
